### PR TITLE
Add Spanish language

### PR DESCRIPTION
**Pull request by pataquets**
I'm mostly done on this. As I can't test the skill myself, I have a doubt I can't check:
* In `languages.go`, the `SpellingHint` string, when is it used and what for? Can you provide more context or an example usage?
I'm tentatively sending a translated string in my PR, but I will adjust it, if needed.

Also, corrected a few spelling mistakes, fixed in its own commit for easier review.

### CODE REVIEW

**Comment by petergtz** [comment]
Hey @pataquets, thanks so much! That's great.

> the SpellingHint string, when is it used and what for? Can you provide more context or an example usage?

When the skill determines that you've searched for the same term twice within relatively short time, the skill assumes that you weren't happy the first time you searched for it and now you're trying again. But now since it's offering the exact term the second time, it assumes you might be even less happy. So it offers you to spell your search instead. And so it tells you what to say so you can spell your search. Judging from Google Translate, the Spanish translation of it actually looks.

I'll merge this. Also, thanks for the spelling fixes 🙈.

**Comment by pataquets** [comment]
@petergtz  then

> Hey @pataquets, thanks so much! That's great.
> 
> > the SpellingHint string, when is it used and what for? Can you provide more context or an example usage?
> 
> When the skill determines that you've searched for the same term twice within relatively short time, the skill assumes that you weren't happy the first time you searched for it and now you're trying again. But now since it's offering the exact term the second time, it assumes you might be even less happy. So it offers you to spell your search instead. And so it tells you what to say so you can spell your search. Judging from Google Translate, the Spanish translation of it actually looks.
> 

Great. My guess was something along those lines. The string will work as is.

> I'll merge this. Also, thanks for the spelling fixes 🙈.

Don't mention it 😄.

Also, aside from getting an ETA for the skill to be available, since I'm not familiar with ASK, what will take to deploy it? Have you considered using Github Actions? Judging by #12, looks like it's on your to-do.

**Comment by pataquets** [comment]
@petergtz ping

**Comment by petergtz** [comment]
Hey @pataquets, sorry, this is taking a bit longer than expected, because the Alexa developer console is giving me an error when trying to certify the new version:
> One or more of the example phrases returned an error response when tested. Please make sure that the example phrases do not provide users with error responses.
> Skill Response for Example Phrase:
> alexa öffne meine enzyklopädie und suche nach käsekuchen

It's a bit bogus, because this is not even the part we've changed. And when trying to reproduce this in the simulator everything works actually. So I will need more time to figure out what's wrong.

I've seen that the Alexa developer console has added additional checks over time. So it's not totally unexpected that those new checks fail. Still, it's a bit strange.

**Comment by petergtz** [comment]
@pataquets Okay, I could fix this with an unrelated change (https://github.com/petergtz/alexa-wikipedia/commit/6558e10fbcf517848c2d298b9a6326ee8a93270e). Now it's submitted and in review. Submission says:
> Results should be available by 11/01/2022, 8:06 PM.

Prepare for more waiting :grimacing:

**Comment by pataquets** [comment]
Thanks for working it out.

> @pataquets Okay, I could fix this with an unrelated change ([6558e10](https://github.com/petergtz/alexa-wikipedia/commit/6558e10fbcf517848c2d298b9a6326ee8a93270e)). Now it's submitted and in review.

I guess Amazon fixed it on their end... 🤔 

> Submission says:
> 
> > Results should be available by 11/01/2022, 8:06 PM.
> 
> Prepare for more waiting 😬

So, wait it is. At least, it's not as bad as when I initially interpreted the date as Spanish (ddmmyyyy). 😅

**Comment by petergtz** [comment]
@pataquets okay, surprise, it's already live. You should be able to try it out.

**Pull request merged**
